"""Regression test: Word comments must use the standard `w:` namespace prefix.

The bug this guards against: when whetstone builds a brand-new
``word/comments.xml`` for a document that had no comments before, an
lxml root created without an explicit ``nsmap`` serialises under the
auto-generated ``ns0:`` prefix. Microsoft Word looks for the ``w:``
prefix specifically and silently ignores comments under any other
prefix — so the comments end up in the file but invisible to the user.

This test builds a real .docx, applies a comment patch through the
production finalisation path, re-opens the resulting zip, and asserts
that every WordprocessingML element in every part uses the ``w:``
prefix (no ``ns0:`` / ``ns1:`` / etc.).
"""

from __future__ import annotations

import re
import zipfile
from pathlib import Path

from docx import Document as DocxDocument

from andamentum.whetstone.docx.finalization import finalize_reviewed_document
from andamentum.whetstone.models import DocumentPatch

WORDML_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"


def _make_source_docx(path: Path, body_text: str) -> None:
    """Write a minimal source .docx containing one paragraph of body_text."""
    doc = DocxDocument()
    doc.add_paragraph(body_text)
    doc.save(str(path))


def _wordml_prefixes_in_part(xml_bytes: bytes) -> set[str]:
    """Return the set of namespace prefixes bound to the WordprocessingML URI
    in one XML part."""
    text = xml_bytes.decode("utf-8", errors="replace")
    # Match xmlns:PREFIX="...wordprocessingml..." declarations.
    prefixes = set(
        re.findall(
            rf'xmlns:([A-Za-z0-9_]+)="{re.escape(WORDML_NS)}"',
            text,
        )
    )
    # Also catch a default (prefix-less) binding, recorded as "" (sentinel).
    if re.search(rf'xmlns="{re.escape(WORDML_NS)}"', text):
        prefixes.add("")
    return prefixes


def test_new_comments_part_uses_w_prefix(tmp_path: Path) -> None:
    """A comment applied to a doc with no prior comments must land in a
    comments.xml that binds the WordprocessingML namespace to `w:`."""
    src = tmp_path / "source.docx"
    out = tmp_path / "reviewed.docx"
    anchor = "The quick brown fox jumps over the lazy dog."
    _make_source_docx(src, anchor)

    patch = DocumentPatch(
        patch_type="comment",
        text_pattern="quick brown fox",
        comment_text="Consider a less clichéd example sentence.",
        explanation="style",
    )

    _, patch_result = finalize_reviewed_document(
        original_file_path=src,
        patches=[patch],
        output_path=out,
        author="test",
    )

    # The comment must have actually applied (anchor exists in the body).
    assert patch_result.applied_patches >= 1, (
        f"comment did not apply: {patch_result.failed_patches}"
    )

    with zipfile.ZipFile(out) as z:
        assert "word/comments.xml" in z.namelist(), "no comments.xml in output"
        comments_xml = z.read("word/comments.xml")

    prefixes = _wordml_prefixes_in_part(comments_xml)
    # The WordprocessingML namespace must be bound to `w` (or be the default
    # namespace). It must NOT be bound to an auto-generated ns0/ns1/... prefix.
    assert prefixes, "comments.xml does not declare the WordprocessingML namespace"
    bad = {p for p in prefixes if p not in ("w", "")}
    assert not bad, (
        f"comments.xml binds the WordprocessingML namespace to non-standard "
        f"prefix(es) {bad} — Word will ignore the comments. Expected 'w'."
    )
    assert "w" in prefixes, (
        f"comments.xml must bind the WordprocessingML namespace to 'w:'; "
        f"got prefixes {prefixes}"
    )

    # Belt-and-braces: there should be no literal `ns0:comment` tag.
    assert b"ns0:comment" not in comments_xml, (
        "comments.xml contains ns0:comment tags — Word will not display them"
    )


def test_all_parts_avoid_autogenerated_wordml_prefix(tmp_path: Path) -> None:
    """Across every XML part whetstone writes, the WordprocessingML namespace
    is never bound to an auto-generated prefix."""
    src = tmp_path / "source.docx"
    out = tmp_path / "reviewed.docx"
    _make_source_docx(src, "Alpha beta gamma delta epsilon zeta eta theta.")

    patches = [
        DocumentPatch(
            patch_type="comment",
            text_pattern="beta gamma",
            comment_text="first comment",
            explanation="x",
        ),
        DocumentPatch(
            patch_type="comment",
            text_pattern="epsilon zeta",
            comment_text="second comment",
            explanation="y",
        ),
    ]

    finalize_reviewed_document(
        original_file_path=src,
        patches=patches,
        output_path=out,
        author="test",
    )

    with zipfile.ZipFile(out) as z:
        xml_parts = [n for n in z.namelist() if n.endswith(".xml")]
        for part in xml_parts:
            data = z.read(part)
            prefixes = _wordml_prefixes_in_part(data)
            bad = {p for p in prefixes if p not in ("w", "")}
            assert not bad, (
                f"{part} binds the WordprocessingML namespace to non-standard "
                f"prefix(es) {bad} — Word may ignore that part's content."
            )
