"""Phase 0 regression test for the document_store chunker swap.

Pins the contract that the new chunker (andamentum.chunker via the adapter
in document_store/chunker_adapter.py) must satisfy when swapped in:

  * chunk count is ≤ what the simple chunker produced
  * coverage of source text is ≥ 95%
  * section_path is recovered for every chunk that lives under a heading
  * source[start:end] == chunk.text round-trip is byte-identical

The baselines under fixtures/chunker_baseline/*.simple_chunker.json were
generated by ``chunk_markdown(text, max_tokens=500, overlap_tokens=50)``
on each fixture in this directory.

Allowed to FAIL until Phase 2 wires the new chunker in. Imports are
deferred inside test bodies so the file collects even before the adapter
module exists.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path

import pytest

FIXTURES = Path(__file__).parent / "fixtures" / "chunker_baseline"
FIXTURE_NAMES = ["short_note", "meeting_log", "paper"]


def _fake_embedder():
    """Deterministic 8-dim embedder for tests — no Ollama required.

    Hashes input strings into a stable pseudo-random vector. Cosine drops
    between truly different paragraphs come out reasonably bimodal (random
    vectors in 8 dims have low expected pairwise cosine), so the chunker's
    semantic split picks defensible boundaries for the regression check.
    """

    async def embed(texts: list[str]) -> list[list[float]]:
        out: list[list[float]] = []
        for t in texts:
            h = hashlib.sha256(t.encode("utf-8")).digest()
            # 8 dims from the first 32 bytes (4 bytes per dim, signed)
            vec = [
                int.from_bytes(h[i : i + 4], "big", signed=True) / 2**31
                for i in range(0, 32, 4)
            ]
            # L2-normalise
            norm = math.sqrt(sum(v * v for v in vec)) or 1.0
            out.append([v / norm for v in vec])
        return out

    return embed


def _load_baseline(name: str) -> tuple[str, dict]:
    src = (FIXTURES / f"{name}.md").read_text()
    baseline = json.loads((FIXTURES / f"{name}.simple_chunker.json").read_text())
    return src, baseline


@pytest.mark.parametrize("name", FIXTURE_NAMES)
async def test_new_chunker_byte_identical_round_trip(name: str):
    """Every chunk's text equals the source slice it was cut from."""
    from andamentum.document_store.chunker_adapter import (  # noqa: PLC0415
        units_to_chunks,
    )
    from andamentum.chunker import extract_units  # noqa: PLC0415

    src, _ = _load_baseline(name)
    result = await extract_units(
        src,
        target_min_chars=1500,
        target_max_chars=4000,
        embedding_fn=_fake_embedder(),
    )
    chunks = units_to_chunks(src, result.units)
    for c in chunks:
        assert src[c.start_char : c.end_char] == c.text, (
            f"{name} chunk {c.chunk_index}: byte-identical round-trip failed"
        )


@pytest.mark.parametrize("name", FIXTURE_NAMES)
async def test_new_chunker_section_path_recovered(name: str):
    """Every chunk that lives under a heading must have a non-empty section_path."""
    from andamentum.document_store.chunker_adapter import (  # noqa: PLC0415
        units_to_chunks,
    )
    from andamentum.chunker import extract_units  # noqa: PLC0415

    src, baseline = _load_baseline(name)
    result = await extract_units(
        src,
        target_min_chars=1500,
        target_max_chars=4000,
        embedding_fn=_fake_embedder(),
    )
    chunks = units_to_chunks(src, result.units)

    if not baseline["unique_section_paths"]:
        # short_note has no headings; nothing to recover
        return

    chunks_with_path = [c for c in chunks if c.section_path]
    assert chunks_with_path, f"{name}: expected some chunks with section_path, got none"


@pytest.mark.parametrize("name", FIXTURE_NAMES)
async def test_new_chunker_count_at_or_below_baseline(name: str):
    """The new chunker should not produce MORE chunks than the simple one."""
    from andamentum.document_store.chunker_adapter import (  # noqa: PLC0415
        units_to_chunks,
    )
    from andamentum.chunker import extract_units  # noqa: PLC0415

    src, baseline = _load_baseline(name)
    result = await extract_units(
        src,
        target_min_chars=1500,
        target_max_chars=4000,
        embedding_fn=_fake_embedder(),
    )
    chunks = units_to_chunks(src, result.units)
    assert len(chunks) <= baseline["chunk_count"], (
        f"{name}: new chunker produced {len(chunks)} chunks, "
        f"simple chunker produced {baseline['chunk_count']}"
    )


@pytest.mark.parametrize("name", FIXTURE_NAMES)
async def test_new_chunker_coverage_at_least_95_percent(name: str):
    """Sum of chunk spans should cover ≥ 95% of source chars."""
    from andamentum.document_store.chunker_adapter import (  # noqa: PLC0415
        units_to_chunks,
    )
    from andamentum.chunker import extract_units  # noqa: PLC0415

    src, _ = _load_baseline(name)
    result = await extract_units(
        src,
        target_min_chars=1500,
        target_max_chars=4000,
        embedding_fn=_fake_embedder(),
    )
    chunks = units_to_chunks(src, result.units)
    covered = sum(c.end_char - c.start_char for c in chunks)
    coverage = covered / len(src)
    assert coverage >= 0.95, (
        f"{name}: coverage {coverage:.3f} below 0.95 threshold "
        f"({covered}/{len(src)} chars)"
    )
